export { default as Home } from './home/Home';
export { default as Foodmenu } from './foodmenu/Foodmenu';
export { default as Contact } from './contact/Contact';
export { default as Categories } from './categories/Categories';
export { default as Pickup } from './pickup/Pickup';
export { default as Events } from './events/Events';
export { default as Delivery } from './delivery/Delivery';
export { default as Navbar } from './navbar/Navbar';
export { default as Services } from './services/Services';
export { default as menu} from './data';